### ISSUE TITLE
Scenario 1: Create the commits database (/commits-sheet-create)

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/PGT_LeaderBot#1]
User Story
As an Admin User, 
I want to generate a database,
So that I can see all the raw data: user handles and github repositories _**and Commits.**_

Acceptance Criteria
Given That I want to see the users raw data,
When I run the /commits-DB,
Then I will see the list of users and commits organized in a google sheet.

**Comment by berkingurcan** [comment]
Hello @CristinaEche  I have couple of questions:
- What do you mean by "raw data"? 
- Considering "generating a database" the data will be in google sheets?
- When you run /commits-DB command, getting list of users and their commits, do you want to see qualified commit number or the full commit data including their code?

**Comment by CristinaEche** [comment]
Hi!, 
1- Raw data is the main database with all of the info gathered from github with user handles and commits
2- Yes database should be available in google drive sheets
3- full commits data .. is it too much info? if too much we can consider other options, let's chat!

**Comment by CristinaEche** [comment]
from chat with Berkin:
Full commits data is very large to insert to the google sheets(there is a 50000 character limit). However, we have the data(AI Decisions) in mongo database. So, I can write a discord command to get the specific data in terms of specific user, repo, decision etc.

**Comment by CristinaEche** [comment]
I executed the command /commits-sheet-create:

<img width="620" alt="image" src="https://github.com/user-attachments/assets/103292fd-dc86-4712-a1ee-32b6109edeab">

the bot returns a message informing that a google drive sheet has been created:

<img width="620" alt="image" src="https://github.com/user-attachments/assets/5c06433f-6f42-4326-85b9-9d573eb007ed">
 
Google dirive sheet:

<img width="953" alt="image" src="https://github.com/user-attachments/assets/73bee639-3d7b-4252-acbb-25c6fb7561dc">

From the user point of view is the correct performance
