### ISSUE TITLE
Fix Update User Repositories field if user exists.

### ISSUE THREAD

**Issue by berkingurcan** [MinaFoundation/PGT_LeaderBot#14]
In case of user [exists](https://github.com/MinaFoundation/PGT_LeaderBot/blob/main/github_tracker_bot/bot_functions.py#L179) in db, it does not update user.repositories.

Update it by [using](https://github.com/MinaFoundation/PGT_LeaderBot/blob/main/github_tracker_bot/mongo_data_handler.py#L211) with sheets data.

**Comment by ramazanoacar** [comment]
hello @berkingurcan , can I work on this one, is it okey?
