### ISSUE TITLE
Add Command for All Data of User for Specific Month

### ISSUE THREAD

**Issue by berkingurcan** [MinaFoundation/PGT_LeaderBot#26]
As you can see in this issue https://github.com/MinaFoundation/PGT_LeaderBot/issues/28 , we need to get all database values and export it to see results more clearly.

Create a command which takes username and month(YYYY-MM) then exports csv file the all data.

- [x] Install and setup environment
- [x] Create a discord command like [here](https://github.com/MinaFoundation/PGT_LeaderBot/blob/main/leader_bot/bot.py#L564). It is similar but we need to take inputs: ```py username: str, date: str(YYYY-MM)```
- [x] Create a function in the [helpers.py](https://github.com/MinaFoundation/PGT_LeaderBot/blob/main/leader_bot/helpers.py)
- [x] In the function get necessary data, [data class is here](https://github.com/MinaFoundation/PGT_LeaderBot/blob/main/github_tracker_bot/mongo_data_handler.py#L50). You can use this (db functions)[https://github.com/MinaFoundation/PGT_LeaderBot/blob/main/leader_bot/db_functions.py] or create a new one (here)[https://github.com/MinaFoundation/PGT_LeaderBot/blob/main/leader_bot/db_functions.py]
- [x] Write helper csv writer function for the data in proper format. After that send to me the data format.
- [x] Send it to a user in discord as a reply as in the example command above.
- [x] Do not forget to use [logger](https://github.com/MinaFoundation/PGT_LeaderBot/blob/main/leader_bot/bot.py#L17)!

**Comment by SalmanDeveloperz** [comment]
Hi @berkingurcan, Could you please assign this issue to me?

**Comment by SalmanDeveloperz** [comment]
Hi @berkingurcan, 
I’m working on implementing the command for exporting user data for a specific month as outlined in issue #26., Before I proceed, I would like to clarify a few points:

1. Existing Structure: Which portion of the codebase should I edit to integrate this command? Is there a specific directory or module where commands are typically added?

2. Data Retrieval: Is there a preferred method or function already in place for fetching user data from the database, or should I implement a new data retrieval function?
 
3. Any Additional Requirements: Are there any specific requirements or formats for the CSV file that I should be aware of?

Thank you for your guidance!

**Comment by berkingurcan** [comment]
Hello @SalmanDeveloperz ! I will make the issue more detailed today! Thank you.

**Comment by MadhalasaSJ** [comment]
Hi, @berkingurcan, can I work on this issue?

**Comment by berkingurcan** [comment]
> Hi, @berkingurcan, can I work on this issue?

Assigned.

> Hi @berkingurcan, I’m working on implementing the command for exporting user data for a specific month as outlined in issue #26., Before I proceed, I would like to clarify a few points:
> 
>     1. Existing Structure: Which portion of the codebase should I edit to integrate this command? Is there a specific directory or module where commands are typically added?
> 
>     2. Data Retrieval: Is there a preferred method or function already in place for fetching user data from the database, or should I implement a new data retrieval function?
> 
>     3. Any Additional Requirements: Are there any specific requirements or formats for the CSV file that I should be aware of?
> 
> 
> Thank you for your guidance!

Updated the issue and assigned!

**Comment by SalmanDeveloperz** [comment]
> Updated the issue and assigned!
@berkingurcan  Thank you! I am starting to work on this issue now.

**Comment by ramazanoacar** [comment]
Hello @berkingurcan, it seems the issue is still open, can you assign me?

**Comment by berkingurcan** [comment]
Solved by https://github.com/MinaFoundation/PGT_LeaderBot/pull/34
