### ISSUE TITLE
Add Command For Removing All Data between specific dates

### ISSUE THREAD

**Issue by berkingurcan** [MinaFoundation/PGT_LeaderBot#27]
Sometimes, we need to refresh the db in order to have simple data. Create a command with confirm modal which deletes data between specific dates.

- [x] Install and setup environment
- [x] Create a discord command like [here](https://github.com/MinaFoundation/PGT_LeaderBot/blob/main/leader_bot/bot.py#L564). 
- [x] The command needs to take two inputs: `from: str YYYY-MM-DD, until: str YYYY-MM-DD`
- [x] After running command, there need to pop up (Discord Modal)[https://discordjs.guide/interactions/modals.html#building-and-responding-with-modals], but find it Python version :)
- [x] In the Modal, there need to be 3 input text, and user have to input their username, from date(YYYY-MM-DD), until date(YYYY-MM-DD)
- [x] There needs to be button to confirm, after clicking the button, check if username, from and until matches.
- [x] If matches, find and delete data between the given dates. Data structure is like [this](https://github.com/MinaFoundation/PGT_LeaderBot/blob/main/github_tracker_bot/mongo_data_handler.py#L50).
- [x] **We need to discuss how we can decide to get data between timeframe because MongoDB does not have built in created at.** It is a really hard issue FYI.
- [x] Do not forget to use [logger](https://github.com/MinaFoundation/PGT_LeaderBot/blob/main/leader_bot/bot.py#L17)!

**Comment by ramazanoacar** [comment]
@berkingurcan it seems the issue is still open, can you assign me also?

**Comment by berkingurcan** [comment]
Solved by https://github.com/MinaFoundation/PGT_LeaderBot/pull/37
