### ISSUE TITLE
Update the get-ai-decisions-by-user command for new data class

### ISSUE THREAD

**Issue by berkingurcan** [MinaFoundation/PGT_LeaderBot#35]
Related to this issue: https://github.com/MinaFoundation/PGT_LeaderBot/issues/19

After adding Commit Hashes to AI Decisions class, modify the current [command](https://github.com/MinaFoundation/PGT_LeaderBot?tab=readme-ov-file#get-ai-decisions-by-user) to export csv with updated data.

Consider handling the missing data for previously gotten data.

**Comment by ramazanoacar** [comment]
@berkingurcan can you assign this one to me also? I am familiar with this one after the previous issue

**Comment by ramazanoacar** [comment]
I believe (this)[https://github.com/MinaFoundation/PGT_LeaderBot/pull/36] PR also solves this one.

**Comment by berkingurcan** [comment]
Solved by https://github.com/MinaFoundation/PGT_LeaderBot/pull/36/
