### ISSUE TITLE
Fix update_all_contribution_datas_from_ai_decisions for NoneType user.ai_decisions

### ISSUE THREAD

**Issue by ramazanoacar** [MinaFoundation/PGT_LeaderBot#41]
When updating users iteratively, sometimes we get users with NoneType ai_decisions and hence get this error cannot update their fields that depends on ai_decisions

**Comment by ramazanoacar** [comment]
@berkingurcan

**Comment by berkingurcan** [comment]
Solved in https://github.com/MinaFoundation/PGT_LeaderBot/pull/37
