### ISSUE TITLE
Scenario 8:  Configure settings of the Leaderboard

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/PGT_LeaderBot#8]
User Story
As an Admin User,
I want to configure leaderboard settings such as ranking criteria,
So that I can increase or decrease the contribution days. Or I can Increase or decrease Commits days.

Acceptance Criteria
Given That I want to update the leaderboard ranking settings,
When run the /Leaderboard-edit,
Then I can edit the commit number and commit days.

**Comment by berkingurcan** [comment]
It is already implemented feature, closed.
